AllCops:
  Exclude:
    - db/**/*
    - bin/**/*
    - lib/gnrd/source_factory.rb
Style/RaiseArgs:
  EnforcedStyle: compact
Metrics/CyclomaticComplexity:
  Max: 7
Style/StringLiterals:
  EnforcedStyle: double_quotes
