sudo: required
services:
  - docker
install:
  - sudo pip install docker-compose

script:
  - docker-compose build
  - docker-compose up -d
  - docker-comopose run app rake

branches:
  only:
    - master

