lanugage: ruby
rvm:
  - 2.2
sudo: required
services:
  - docker
  - redis-server
install:
  - docker run -d --name nn -p 0.0.0.0:6384:6384 gnames/netineti
  - docker run -d --name tf -p 0.0.0.0:1234:1234 gnames/taxonfinder
  - sudo apt-get update
  - sudo apt-get install graphicsmagick
  - sudo apt-get install --fix-missing poppler-utils
  - sudo apt-get install --fix-missing poppler-data
  - sudo apt-get install ghostscript
  - sudo apt-get install tesseract-ocr
  - sudo apt-get install pdftk
  - sudo apt-get install libreoffice
  - sudo apt-get install libmagic-dev
  - sudo apt-get install wget
  - cp config/config.yml.example config/config.yml 

branches:
  only:
    - master

