lanugage: ruby
rvm:
  - 2.2
sudo: required
services:
  - docker
  - redis-server
bundler_args: --without development
before_install:
  - docker run -d --name nn -p 0.0.0.0:6384:6384 gnames/netineti
  - docker run -d --name tf -p 0.0.0.0:1234:1234 gnames/taxonfinder
  - sudo apt-get update
  - sudo apt-get -qy install graphicsmagick
  - sudo apt-get -qy install --fix-missing poppler-utils
  - sudo apt-get -qy install --fix-missing poppler-data
  - sudo apt-get -qy install ghostscript
  - sudo apt-get -qy install tesseract-ocr
  - sudo apt-get -qy install pdftk
  - sudo apt-get -qy install libreoffice
  - sudo apt-get -qy install libmagic-dev
  - sudo apt-get -qy install wget
  - cp config/config.yml.example config/config.yml 

branches:
  only:
    - master

