sudo: required
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
bundler_args: --without development
services:
  - redis-server
  - docker
  - postgresql
addons:
  postgresql: "9.4"
before_install:
  - docker run -d --name nn -p 0.0.0.0:6384:6384 gnames/netineti
  - docker run -d --name tf -p 0.0.0.0:1234:1234 gnames/taxonfinder
  - sudo apt-get update
  - sudo apt-get -qy install graphicsmagick
  - sudo apt-get -qy install --fix-missing poppler-utils
  - sudo apt-get -qy install --fix-missing poppler-data
  - sudo apt-get -qy install ghostscript
  - sudo apt-get -qy install tesseract-ocr
  - sudo apt-get -qy install pdftk
  - sudo apt-get -qy install libreoffice
  - sudo apt-get -qy install libmagic-dev
  - sudo apt-get -qy install wget
  - cp config/config.json.example config/config.json
  - gem install bundler
before_script:
  - bundle exec rake db:setup
  - QUEUE=gnrd TERM_CHILD=1 rake resque:work &
branches:
  only:
    - master
