sudo: required
language: ruby
rvm:
  - 2.6
bundler_args: --without development
services:
  - redis-server
  - docker
  - postgresql
addons:
  postgresql: "9.6"
before_install:
  - docker run -d --name gnf -p 0.0.0.0:8778:8778 gnames/gnfinder:v0.9.0
  - sudo apt-get update
  - sudo apt-get -qy install graphicsmagick
  - sudo apt-get -qy install --fix-missing poppler-utils
  - sudo apt-get -qy install --fix-missing poppler-data
  - sudo apt-get -qy install ghostscript
  - sudo apt-get -qy install tesseract-ocr
  - sudo apt-get -qy install pdftk
  - sudo apt-get -qy install libreoffice
  - sudo apt-get -qy install libmagic-dev
  - sudo apt-get -qy install wget
  - gem install bundler
  - export RACK_ENV=test
  - export RESQUE_WORKERS=1
  - REDIS_HOST=0.0.0.0
  - export GNRD_SALT=test
  - export GNFINDER_HOST=0.0.0.0
  - export GNFINDER_PORT=8778
  - GNRD_DB_HOST=0.0.0.0
  - GNRD_DB_USER=postgres
  - GNRD_DB_USER_PASSWORD=''
before_script:
  - bundle exec rake db:setup
  - QUEUE=gnrd TERM_CHILD=1 rake resque:work &
branches:
  only:
    - master
