sudo: required
services:
  - docker
install:
  - sudo -H pip install "docker-compose=1.4.1"

script:
  - docker-compose build
  - docker-compose up -d
  - docker-comopose run app rake

branches:
  only:
    - master

