version: '2'
services:
  app:
    build:
      context: .
    container_name: gnrd
    image: gnames/gnrd
    ports:
      - "0.0.0.0:9292:80"
    depends_on:
      - nn
      - tf
      - redis
      - pg
    env_file: .env
    environment:
      RACK_ENV: production
      GNRD_DB_HOST: pg
      GNRD_DB: gnrd
      RESQUE_WORKERS: 1
  redis:
    image: redis
  nn:
    image: gnames/netineti
  tf:
    image: gnames/taxonfinder
  pg:
    image: postgres
    volumes:
      - /opt/gna/data/gnrd/postgresql/data:/var/lib/postgresql/data
