version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: gnrd
    image: gnames/gnrd
    ports:
      - "0.0.0.0:9292:80"
    depends_on:
      - gnf
      - redis
      - pg
    command: [/usr/bin/supervisord, -c, /app/config/docker/supervisord.conf]
  redis:
    image: redis
  gnf:
    image: gnames/gnfinder:v0.9.0
    ports:
      - "0.0.0.0:8778:8778"
  pg:
    image: postgres
    env_file:
      - .env
    volumes:
      - /opt/gna/data/gnrd/postgresql/data:/var/lib/postgresql/data
