version: '3'
services:
  app:
    build: .
    ports:
      - "0.0.0.0:9292:9292"
    volumes:
      - .:/app
    depends_on:
      - nn
      - tf
      - gnf
      - redis
      - pg
  redis:
    image: redis
  nn:
    image: gnames/netineti
  tf:
    image: gnames/taxonfinder
  gnf:
    image: gnames/gnfinder:v0.9.0
    ports:
      - "0.0.0.0:8778:8778"
  pg:
    image: postgres
