version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "0.0.0.0:9292:9292"
      - "0.0.0.0:80:80"
    volumes:
      - .:/app
    depends_on:
      - nn
      - tf
      - gnf
      - redis
      - pgdb
  redis:
    image: redis
  nn:
    image: gnames/netineti
  tf:
    image: gnames/taxonfinder
  gnf:
    image: gnames/gnfinder:v0.8.4
    ports:
      - "0.0.0.0:8778:8778"
  pgdb:
    image: postgres
    ports:
      - "0.0.0.0:5432:5432"
